// src/app/components/audio-manager/audio-manager.component.ts
import {Component, ElementRef, EventEmitter, Input, Output, ViewChild} from '@angular/core';

@Component({
    selector: 'app-audio-manager',
    templateUrl: './audio-manager.component.html',
    styleUrls: ['./audio-manager.component.scss'],
})
export class AudioManagerComponent {
    @Input() public src?: string;

    @Output() private currentTimeChange = new EventEmitter<number>();

    @ViewChild('audio') private audioRef!: ElementRef<HTMLAudioElement>;

    public timeUpdateHandler(): void {
        this.currentTimeChange.emit(this.audioRef.nativeElement.currentTime);
    }

    public backToTopButtonClickHandler(): void {
        window.scrollTo({top: 0});
    }
}

<div class="audio-manager">
    <audio #audio [src]="src" controls muted preload="metadata" (timeupdate)="timeUpdateHandler()"></audio>
    <button class="secondary back-to-top" (click)="backToTopButtonClickHandler()">بازگشت به ابتدای صفحه</button>
</div>

// src/components/audio-manager/audio-manager.component.tsx
import { ReactNode, useRef } from "react";

import styles from "./audio-manager.module.css";

type Props = {
  src: string;
  onCurrentTimeChange: (time: number) => void;
};

export default function AudioManagerComponent({
  src,
  onCurrentTimeChange,
}: Props): ReactNode {
  const audioRef = useRef<HTMLAudioElement>(null);

  const timeUpdateHandler = (): void => {
    onCurrentTimeChange(audioRef.current!.currentTime);
  };

  const backToTopButtonClickHandler = (): void => {
    window.scrollTo({ top: 0 });
  };

  return (
    <div className={styles["audio-manager"]}>
      <audio
        ref={audioRef}
        src={src || undefined}
        controls
        muted
        preload="metadata"
        onTimeUpdate={timeUpdateHandler}
      />
      <button
        className="button secondary back-to-top"
        onClick={backToTopButtonClickHandler}
      >
        بازگشت به ابتدای صفحه
      </button>
    </div>
  );
}
